-- Baseline: Esquema actual en producción
-- Este script documenta el estado REAL actual de la base de datos

-- Tabla sorteos
CREATE TABLE IF NOT EXISTS sorteos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL,
    fecha_creacion TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    importe_maximo DOUBLE PRECISION,
    importe_minimo DOUBLE PRECISION,
    nombre VARCHAR(255) NOT NULL,
    nombre_interno VARCHAR(255)
);

-- Tabla participantes (sin campos de password, role, ni tallas)
CREATE TABLE IF NOT EXISTS participantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asignado_a VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    genero VARCHAR(10),
    nombre VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    sorteo_id BIGINT NOT NULL,
    CONSTRAINT uk_token UNIQUE (token),
    CONSTRAINT uk_sorteo_email UNIQUE (sorteo_id, email),
    CONSTRAINT fktnmx6soac4el2fof3lh2v1pb7 FOREIGN KEY (sorteo_id) REFERENCES sorteos(id)
);
