-- V2: Refactorización del modelo de datos
-- Separar usuarios de participaciones en sorteos (sin modificar participantes)

-- 1. Crear tabla usuarios (email único con password única)
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    genero VARCHAR(10),
    role VARCHAR(50) DEFAULT 'USER',
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Crear tabla perfil_sorteo (tallas y preferencias por sorteo)
CREATE TABLE IF NOT EXISTS perfil_sorteo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    sorteo_id BIGINT NOT NULL,
    token VARCHAR(255) UNIQUE,
    asignado_a VARCHAR(255),
    talla_camisa VARCHAR(50),
    talla_pantalon VARCHAR(50),
    talla_zapato VARCHAR(50),
    talla_chaqueta VARCHAR(50),
    preferencias TEXT,
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_sorteo_perfil FOREIGN KEY (sorteo_id) REFERENCES sorteos(id) ON DELETE CASCADE,
    CONSTRAINT uk_usuario_sorteo UNIQUE (usuario_id, sorteo_id)
);

-- 3. Migrar datos de participantes a usuarios y perfil_sorteo
-- Paso 3a: Insertar usuarios únicos (agrupa por email)
-- NOTA: Password se genera al enviar email, aquí hash BCrypt inválido como placeholder
INSERT INTO usuarios (email, password, nombre, genero, role, fecha_creacion)
SELECT DISTINCT ON (email) 
    email,
    '$2b$12$invalidinvalidinvalidinvalidinv',  -- Placeholder: hash inválido, se genera al regenerar password
    nombre,
    genero,
    'USER',
    CURRENT_TIMESTAMP
FROM participantes
ORDER BY email, id ASC
ON CONFLICT (email) DO NOTHING;

-- Paso 3b: Crear perfiles de sorteo para cada participación
INSERT INTO perfil_sorteo (usuario_id, sorteo_id, token, asignado_a, talla_camisa, talla_pantalon, talla_zapato, talla_chaqueta, preferencias)
SELECT 
    u.id,
    p.sorteo_id,
    p.token,
    p.asignado_a,
    NULL, -- tallas no existen en participantes legacy
    NULL,
    NULL,
    NULL,
    NULL  -- preferencias no existen en participantes legacy
FROM participantes p
INNER JOIN usuarios u ON u.email = p.email
WHERE p.sorteo_id IS NOT NULL;

-- 4. Índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON usuarios(email);
CREATE INDEX IF NOT EXISTS idx_perfil_sorteo_usuario ON perfil_sorteo(usuario_id);
CREATE INDEX IF NOT EXISTS idx_perfil_sorteo_sorteo ON perfil_sorteo(sorteo_id);
CREATE INDEX IF NOT EXISTS idx_perfil_sorteo_token ON perfil_sorteo(token);
CREATE INDEX IF NOT EXISTS idx_perfil_sorteo_asignado ON perfil_sorteo(asignado_a);

-- 5. Comentarios finales
-- NOTA: La tabla participantes se mantiene intacta como backup/legacy
-- NO se añaden columnas nuevas (password, role, tallas) a participantes
-- Toda la lógica nueva usa usuarios + perfil_sorteo
-- participantes solo existe para compatibilidad histórica y rollback seguro
