-- V2: Refactorización del modelo de datos
-- Agregar campos faltantes y separar usuarios de participaciones en sorteos

-- 1. Agregar campos que faltan en participantes (para compatibilidad temporal)
ALTER TABLE participantes ADD COLUMN IF NOT EXISTS password VARCHAR(255);
ALTER TABLE participantes ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'USER';
ALTER TABLE participantes ADD COLUMN IF NOT EXISTS talla_camisa VARCHAR(50);
ALTER TABLE participantes ADD COLUMN IF NOT EXISTS talla_pantalon VARCHAR(50);
ALTER TABLE participantes ADD COLUMN IF NOT EXISTS talla_zapato VARCHAR(50);
ALTER TABLE participantes ADD COLUMN IF NOT EXISTS talla_chaqueta VARCHAR(50);
ALTER TABLE participantes ADD COLUMN IF NOT EXISTS preferencias TEXT;

-- 2. Crear tabla usuarios (email único con password única)
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    genero VARCHAR(10),
    role VARCHAR(50) DEFAULT 'USER',
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Crear tabla perfil_sorteo (tallas y preferencias por sorteo)
CREATE TABLE IF NOT EXISTS perfil_sorteo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    sorteo_id BIGINT NOT NULL,
    token VARCHAR(255) UNIQUE,
    asignado_a VARCHAR(255),
    talla_camisa VARCHAR(50),
    talla_pantalon VARCHAR(50),
    talla_zapato VARCHAR(50),
    talla_chaqueta VARCHAR(50),
    preferencias TEXT,
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_sorteo_perfil FOREIGN KEY (sorteo_id) REFERENCES sorteos(id) ON DELETE CASCADE,
    CONSTRAINT uk_usuario_sorteo UNIQUE (usuario_id, sorteo_id)
);

-- 4. Migrar datos de participantes a usuarios y perfil_sorteo
-- Paso 4a: Insertar usuarios únicos (agrupa por email)
INSERT INTO usuarios (email, password, nombre, genero, role, fecha_creacion)
SELECT DISTINCT ON (email) 
    email,
    COALESCE(password, 'TEMP_PASSWORD_' || MD5(email || CURRENT_TIMESTAMP::text)),
    nombre,
    genero,
    COALESCE(role, 'USER'),
    CURRENT_TIMESTAMP
FROM participantes
ORDER BY email, id ASC
ON CONFLICT (email) DO NOTHING;

-- Paso 4b: Crear perfiles de sorteo para cada participación
INSERT INTO perfil_sorteo (usuario_id, sorteo_id, token, asignado_a, talla_camisa, talla_pantalon, talla_zapato, talla_chaqueta, preferencias)
SELECT 
    u.id,
    p.sorteo_id,
    p.token,
    p.asignado_a,
    p.talla_camisa,
    p.talla_pantalon,
    p.talla_zapato,
    p.talla_chaqueta,
    p.preferencias
FROM participantes p
INNER JOIN usuarios u ON u.email = p.email
WHERE p.sorteo_id IS NOT NULL;

-- 5. Índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON usuarios(email);
CREATE INDEX IF NOT EXISTS idx_perfil_sorteo_usuario ON perfil_sorteo(usuario_id);
CREATE INDEX IF NOT EXISTS idx_perfil_sorteo_sorteo ON perfil_sorteo(sorteo_id);
CREATE INDEX IF NOT EXISTS idx_perfil_sorteo_token ON perfil_sorteo(token);
CREATE INDEX IF NOT EXISTS idx_perfil_sorteo_asignado ON perfil_sorteo(asignado_a);

-- 6. NO eliminamos la tabla participantes todavía para permitir rollback seguro
-- Comentario: La tabla participantes se mantiene por ahora para compatibilidad
-- Se eliminará en una migración posterior (V3) después de validar en producción
